# ------------------------
# Render service configuration
# ------------------------
services:
  - type: web
    name: NewsArticles
    env: python
    plan: free  # change to standard if needed
    region: oregon  # or choose your preferred region
    buildCommand: bash build.sh
    startCommand: gunicorn newsportal.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: RENDER_ENV
        value: production
      - key: SECRET_KEY
        value: django-insecure-3f!8y@v$k#r2z%1m7b&d3o8h!s6p@e#q4j+1w^u%t!n7l&f
      - key: FLW_SECRET_KEY
        value: <your-flutterwave-secret-key>
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: StrongPassword123
      - key: DATABASE_URL
        value: <your-prod-db-url>  # optional if using Postgres
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: eaglecollins.onrender.com
    autoDeploy: true
    repo: https://github.com/ositaejiofor/NewsArticles
