services:
  - type: web
    name: newsportal
    env: python
    region: oregon
    branch: main
    plan: free
    buildCommand: bash ./build.sh
    startCommand: bash ./start.sh
    envVars:
      - key: SECRET_KEY
        value: replace_with_your_secret_key
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: yourdomain.com,www.yourdomain.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: youremail@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: StrongPassword123
      - key: FLUTTERWAVE_SECRET_KEY
        value: replace_with_flutterwave_key
      - key: SENDGRID_API_KEY
        value: replace_with_sendgrid_key
      - key: DATABASE_URL
        fromDatabase: true
