services:
  - type: web
    name: newsportal
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: gunicorn newsportal.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: RENDER_ENV
        value: production
      - key: SECRET_KEY
        fromDatabase: true
      - key: FLW_SECRET_KEY
        fromDatabase: true
      - key: DATABASE_URL
        fromDatabase: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: eaglecollins.onrender.com
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        fromDatabase: true
      - key: EMAIL_HOST_PASSWORD
        fromDatabase: true
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USE_SSL
        value: "False"
