services:
  - type: web
    name: newsportal-web
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: gunicorn newsportal.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        fromDatabase: true
      - key: DEBUG
        value: 'False'
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        fromDatabase: true
