services:
  - type: web
    name: newsportal
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn newsportal.wsgi:application --workers=4 --bind=0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: newsportal-db
          property: connectionString
      # Superuser credentials must be added manually in Render Dashboard:
      # DJANGO_SUPERUSER_USERNAME
      # DJANGO_SUPERUSER_EMAIL
      # DJANGO_SUPERUSER_PASSWORD
databases:
  - name: newsportal-db
    plan: free
