# =========================
# Render Blueprint
# =========================
services:
  - type: web
    name: newsportal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn newsportal.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false   # set this securely in Render dashboard
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "newsportal.onrender.com,yourcustomdomain.com"
      - key: RENDER_ENV
        value: "production"
      - key: DB_NAME
        fromDatabase:
          name: newsportal-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: newsportal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: newsportal-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: newsportal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: newsportal-db
          property: port

databases:
  - name: newsportal-db
    databaseName: newsportal
    user: newsportal
