services:
  - type: web
    name: news-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn newsportal.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: RENDER_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: news-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLW_SECRET_KEY
        sync: false
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USE_SSL
        value: "False"

databases:
  - name: news-db
    plan: free
