# Generated by Django 5.2.6 on 2025-09-12 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('stacked', 'Stacked Bar Chart')], default='bar', max_length=20)),
                ('cumulative', models.BooleanField(default=False)),
                ('time_range', models.CharField(choices=[('month', 'Per Month'), ('year', 'Per Year'), ('all', 'All Time'), ('custom', 'Custom Range')], default='month', max_length=20)),
                ('custom_start', models.DateField(blank=True, null=True)),
                ('custom_end', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
