# Generated by Django 5.2.6 on 2025-09-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_author_remove_post_category_article'),
        ('comments', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
