# Generated by Django 5.2.6 on 2025-09-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Short summary or excerpt of the article', max_length=500),
        ),
    ]
